import { prisma } from "../../db/prisma";
import type { AlertType } from "./types";

const MATCH_TOLERANCE = 1.0;
const DATE_WINDOW_DAYS = 3;

interface L1L2Result {
  matched: number;
  unmatched: number;
  discrepancies: number;
  alerts: Array<{ type: AlertType; message: string; details: string }>;
}

/**
 * Reset all reconciliation links to allow a clean re-run.
 * Clears L1→L2 links, L2→L3 links, computed fields, and auto-resolves alerts.
 */
export async function resetReconciliationLinks(): Promise<{
  ordersReset: number;
  transactionsReset: number;
  payoutsReset: number;
  bankTransactionsReset: number;
  alertsResolved: number;
}> {
  return prisma.$transaction(async (tx) => {
    // Reset L1: clear order → payout links
    const ordersResult = await tx.platformOrder.updateMany({
      where: { linkedPayoutId: { not: null } },
      data: { linkedPayoutId: null, reconciliationStatus: "unreconciled" },
    });

    // Reset L1: clear transaction → payout/bank links
    const txResult = await tx.transaction.updateMany({
      where: {
        OR: [
          { linkedPayoutId: { not: null } },
          { linkedBankTransactionId: { not: null } },
        ],
      },
      data: {
        linkedPayoutId: null,
        linkedBankTransactionId: null,
        reconciliationStatus: "unreconciled",
      },
    });

    // Reset L2: clear payout → bank links and computed fields
    const payoutsResult = await tx.payout.updateMany({
      data: {
        bankTransactionId: null,
        reconciliationStatus: "unreconciled",
        expectedAmount: null,
        amountVariance: null,
      },
    });

    // Reset L3: unreconcile bank transactions
    const bankResult = await tx.bankTransaction.updateMany({
      where: { reconciled: true },
      data: { reconciled: false, reconciliationStatus: "unreconciled" },
    });

    // Auto-resolve all existing alerts (they'll be regenerated by the scan)
    const alertsResult = await tx.reconciliationAlert.updateMany({
      where: { resolved: false },
      data: {
        resolved: true,
        resolvedAt: new Date(),
        resolvedBy: "system_reset",
      },
    });

    return {
      ordersReset: ordersResult.count,
      transactionsReset: txResult.count,
      payoutsReset: payoutsResult.count,
      bankTransactionsReset: bankResult.count,
      alertsResolved: alertsResult.count,
    };
  });
}

/**
 * Match L1 atomic events (PlatformOrders) to L2 payouts.
 * Strategy: use platform payout IDs first (deterministic), then fall back
 * to date-window matching for platforms without payout IDs.
 */
export async function matchLevel1ToLevel2(
  platform?: string
): Promise<L1L2Result> {
  const platforms = platform
    ? [platform]
    : ["doordash", "ubereats", "grubhub", "square"];

  const combined: L1L2Result = {
    matched: 0,
    unmatched: 0,
    discrepancies: 0,
    alerts: [],
  };

  for (const p of platforms) {
    const result = await matchPlatform(p);
    combined.matched += result.matched;
    combined.unmatched += result.unmatched;
    combined.discrepancies += result.discrepancies;
    combined.alerts.push(...result.alerts);
  }

  return combined;
}

async function matchPlatform(platform: string): Promise<L1L2Result> {
  const result: L1L2Result = {
    matched: 0,
    unmatched: 0,
    discrepancies: 0,
    alerts: [],
  };

  // Get all payouts for this platform
  const payouts = await prisma.payout.findMany({
    where: { platform },
    orderBy: { payoutDate: "asc" },
    include: { platformOrders: true },
  });

  if (payouts.length === 0) {
    // No payouts — try to match orders directly to bank transactions
    await matchOrdersWithoutPayouts(platform, result);
    return result;
  }

  // ── Phase 1: Platform Payout ID Matching (deterministic) ──
  // For platforms like DoorDash where both orders and payouts have a
  // shared platform payout ID, use it for exact matching.
  // Always filter orders by channel (e.g. Marketplace vs Storefront)
  // so that Storefront orders don't inflate a Marketplace-only payout.
  const payoutsWithPlatformId = payouts.filter((p) => p.platformPayoutId);

  for (const payout of payoutsWithPlatformId) {
    // Extract this payout's channel from rawData
    let payoutChannel: string | null = null;
    if (payout.rawData) {
      try {
        const raw = JSON.parse(payout.rawData);
        payoutChannel = raw["Channel"] || raw["channel"] || null;
      } catch {
        /* ignore parse errors */
      }
    }

    // Find orders matching this payout ID
    let matchingOrders = await prisma.platformOrder.findMany({
      where: {
        platform,
        platformPayoutId: payout.platformPayoutId,
        linkedPayoutId: null, // only unlinked
      },
    });

    // Always filter orders by channel when the payout has channel info.
    // This prevents Storefront orders from being linked to a Marketplace
    // payout (and vice versa), even when there's only one payout record
    // for a given payout ID.
    if (payoutChannel) {
      matchingOrders = matchingOrders.filter((order) => {
        if (!order.rawData) return false;
        try {
          const raw = JSON.parse(order.rawData);
          const orderChannel = raw["Channel"] || raw["channel"] || null;
          return orderChannel === payoutChannel;
        } catch {
          return false;
        }
      });
    }

    if (matchingOrders.length === 0) continue;

    // Link orders to this payout
    const orderIds = matchingOrders.map((o) => o.id);
    const orderTotal = matchingOrders.reduce(
      (sum, o) => sum + o.netPayout,
      0
    );
    const variance = Math.abs(orderTotal - payout.netAmount);

    await prisma.platformOrder.updateMany({
      where: { id: { in: orderIds } },
      data: {
        linkedPayoutId: payout.id,
        reconciliationStatus:
          variance <= MATCH_TOLERANCE ? "reconciled" : "discrepancy_detected",
      },
    });

    // Also link matching income transactions
    const rawSourceIds = matchingOrders.map((o) => o.orderId);
    if (rawSourceIds.length > 0) {
      await prisma.transaction.updateMany({
        where: {
          sourcePlatform: platform,
          rawSourceId: { in: rawSourceIds },
          linkedPayoutId: null,
        },
        data: { linkedPayoutId: payout.id },
      });
    }

    // Update payout with computed amounts
    const payoutStatus =
      variance <= MATCH_TOLERANCE
        ? payout.bankTransactionId
          ? "reconciled"
          : "partially_reconciled"
        : "discrepancy_detected";

    await prisma.payout.update({
      where: { id: payout.id },
      data: {
        expectedAmount: orderTotal,
        amountVariance: orderTotal - payout.netAmount,
        reconciliationStatus: payoutStatus,
      },
    });

    if (variance <= MATCH_TOLERANCE) {
      result.matched += matchingOrders.length;
    } else {
      result.discrepancies++;
      result.alerts.push({
        type: "payout_mismatch",
        message: `${platform} payout $${payout.netAmount.toFixed(2)} differs from order total $${orderTotal.toFixed(2)}`,
        details: JSON.stringify({
          payoutId: payout.id,
          payoutAmount: payout.netAmount,
          orderTotal,
          variance: orderTotal - payout.netAmount,
          orderCount: matchingOrders.length,
        }),
      });
    }
  }

  // ── Phase 2: Date-window fallback ──
  // For payouts WITHOUT a platformPayoutId, fall back to date-window matching.
  const payoutsWithoutPlatformId = payouts.filter((p) => !p.platformPayoutId);

  // Re-fetch unlinked orders (some may have been linked in Phase 1)
  const unlinkedOrders = await prisma.platformOrder.findMany({
    where: {
      platform,
      linkedPayoutId: null,
    },
    orderBy: { orderDatetime: "asc" },
  });

  for (const payout of payoutsWithoutPlatformId) {
    const payoutDate = payout.payoutDate.getTime();
    const windowStart = payoutDate - DATE_WINDOW_DAYS * 24 * 60 * 60 * 1000;

    // Find orders that fall before this payout (within window)
    const candidateOrders = unlinkedOrders.filter((o) => {
      const orderTime = o.orderDatetime.getTime();
      return orderTime <= payoutDate && orderTime >= windowStart;
    });

    if (candidateOrders.length === 0) continue;

    // Sum the net payouts of candidate orders
    const orderTotal = candidateOrders.reduce(
      (sum, o) => sum + o.netPayout,
      0
    );
    const variance = Math.abs(orderTotal - payout.netAmount);

    // Link orders to this payout
    const orderIds = candidateOrders.map((o) => o.id);
    await prisma.platformOrder.updateMany({
      where: { id: { in: orderIds } },
      data: {
        linkedPayoutId: payout.id,
        reconciliationStatus:
          variance <= MATCH_TOLERANCE ? "reconciled" : "discrepancy_detected",
      },
    });

    // Also link matching income transactions
    const rawSourceIds = candidateOrders.map((o) => o.orderId);
    if (rawSourceIds.length > 0) {
      await prisma.transaction.updateMany({
        where: {
          sourcePlatform: platform,
          rawSourceId: { in: rawSourceIds },
          linkedPayoutId: null,
        },
        data: { linkedPayoutId: payout.id },
      });
    }

    // Remove linked orders from the unlinked pool
    for (const id of orderIds) {
      const idx = unlinkedOrders.findIndex((o) => o.id === id);
      if (idx >= 0) unlinkedOrders.splice(idx, 1);
    }

    // Update payout with computed amounts
    const payoutStatus =
      variance <= MATCH_TOLERANCE
        ? payout.bankTransactionId
          ? "reconciled"
          : "partially_reconciled"
        : "discrepancy_detected";

    await prisma.payout.update({
      where: { id: payout.id },
      data: {
        expectedAmount: orderTotal,
        amountVariance: orderTotal - payout.netAmount,
        reconciliationStatus: payoutStatus,
      },
    });

    if (variance <= MATCH_TOLERANCE) {
      result.matched += candidateOrders.length;
    } else {
      result.discrepancies++;
      result.alerts.push({
        type: "payout_mismatch",
        message: `${platform} payout $${payout.netAmount.toFixed(2)} differs from order total $${orderTotal.toFixed(2)}`,
        details: JSON.stringify({
          payoutId: payout.id,
          payoutAmount: payout.netAmount,
          orderTotal,
          variance: orderTotal - payout.netAmount,
          orderCount: candidateOrders.length,
        }),
      });
    }
  }

  // Remaining unlinked orders
  result.unmatched += unlinkedOrders.length;

  return result;
}

/**
 * For platforms without explicit payout records (e.g., Square where payouts
 * go directly to bank), try to group daily orders and match to bank transactions.
 */
async function matchOrdersWithoutPayouts(
  platform: string,
  result: L1L2Result
): Promise<void> {
  const unlinkedOrders = await prisma.platformOrder.findMany({
    where: {
      platform,
      linkedPayoutId: null,
    },
    orderBy: { orderDatetime: "asc" },
  });

  if (unlinkedOrders.length === 0) return;

  // Group orders by date
  const dailyGroups = new Map<string, typeof unlinkedOrders>();
  for (const order of unlinkedOrders) {
    const dateKey = order.orderDatetime.toISOString().split("T")[0];
    if (!dailyGroups.has(dateKey)) {
      dailyGroups.set(dateKey, []);
    }
    dailyGroups.get(dateKey)!.push(order);
  }

  // For each daily group, try to find a matching bank transaction
  for (const [dateKey, orders] of dailyGroups) {
    const dailyTotal = orders.reduce((sum, o) => sum + o.netPayout, 0);
    if (dailyTotal === 0) continue;

    const dateStart = new Date(dateKey);
    const dateEnd = new Date(dateKey);
    dateEnd.setDate(dateEnd.getDate() + DATE_WINDOW_DAYS);

    // Look for a bank transaction matching the daily total
    const bankTx = await prisma.bankTransaction.findFirst({
      where: {
        reconciled: false,
        amount: {
          gte: dailyTotal - MATCH_TOLERANCE,
          lte: dailyTotal + MATCH_TOLERANCE,
        },
        date: { gte: dateStart, lte: dateEnd },
        description: { contains: platform },
      },
    });

    if (bankTx) {
      // Link transactions directly to bank transaction
      const orderIds = orders.map((o) => o.id);
      const rawSourceIds = orders.map((o) => o.orderId);

      await prisma.platformOrder.updateMany({
        where: { id: { in: orderIds } },
        data: { reconciliationStatus: "reconciled" },
      });

      if (rawSourceIds.length > 0) {
        await prisma.transaction.updateMany({
          where: {
            sourcePlatform: platform,
            rawSourceId: { in: rawSourceIds },
            linkedBankTransactionId: null,
          },
          data: {
            linkedBankTransactionId: bankTx.id,
            reconciliationStatus: "reconciled",
          },
        });
      }

      await prisma.bankTransaction.update({
        where: { id: bankTx.id },
        data: {
          reconciled: true,
          reconciliationStatus: "reconciled",
        },
      });

      result.matched += orders.length;
    } else {
      result.unmatched += orders.length;
    }
  }
}
